# See https://github.com/helm/chart-testing#configuration
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
remote: origin
target-branch: main
chart-dirs:
  - charts
helm-extra-args: --timeout 60m
debug: true
