# See https://github.com/helm/chart-testing#configuration
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
remote: origin
target-branch: main
chart-dirs:
  - charts/kafka-connect
  - charts/kafka-connect-ui
  - charts/metabase
  - charts/weblate
helm-extra-args: --timeout 30m
debug: true
