apiVersion: v2
appVersion: 0.14.2
description: Weblate is a free web-based translation management system.
name: weblate
type: application
version: 0.0.2
dependencies:
- name: postgresql
  version: 12.1.3
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.3.14
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
home: https://github.com/rdomenzain/helm-chart/tree/main/charts/weblate
maintainers:
  - name: rdomenzain
    url: https://github.com/rdomenzain/
sources:
  - https://github.com/rdomenzain/helm-chart/tree/main/charts/weblate
